#!/bin/sh
umask 0177

CFGFILE=$HOME/.pwrc
[ -f $CFGFILE ] && . $CFGFILE

: ${PWDIR:=$HOME/.pw}
: ${KEYID:=4DEC416A63E41987E0A0DC6A870F721687E49E93}

usage() {
	printf 'usage: %s <set|get|ls> [domain] [user] [passwd]\n' ${0##*/} 1>&2
	exit 0
}

case "$1" in
set)
	shift
	[ $# -ne 3 ] && usage

	[ -d $PWDIR/$1 ] || {
		mkdir -p $PWDIR/$1
		chmod 700 $PWDIR/$1
	}
	echo "$3" | gpg -qaer $KEYID >$PWDIR/$1/$2
	;;
get)
	shift
	case $# in
	1)	gpg -qd <"$PWDIR/$1/`ls -1 $PWDIR/$1/ | head -1`"
		;;
	2)	gpg -qd <"$PWDIR/$1/$2"
		;;
	*)	usage
		;;
	esac
	;;
ls)
	tree $PWDIR
	;;
*)
	usage
	;;
esac

